[package]
name = "rc_05_maze_textures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra-glm = "0.18.0"
minifb = "0.26.0"
image = { version = "0.25", default-features = false, features = ["png"] }

[profile.dev]
opt-level = 3
